default_context:
  project_name: 'sisprot-dev'
  project_slug: 'sisprot-dev'
  domain_main: 'sisprot-dev.com'
  domain_staging: 'stag.sisprot-dev.com'
  docker_swarm_stack_name_main: 'sisprot-dev-com'
  docker_swarm_stack_name_staging: 'stag-sisprot-dev-com'
  secret_key: 'sisprot'
  first_superuser: 'admin'
  first_superuser_password: 'sisprot'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.sisprot-dev.com", "https://stag.sisprot-dev.com", "https://sisprot-dev.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@sisprot-dev.com'
  postgres_password: 'sisprot'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'sisprot'
  traefik_constraint_tag: 'sisprot-dev.com'
  traefik_constraint_tag_staging: 'stag.sisprot-dev.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:sisprot'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
